name: Generate Snake Animation

on:
  schedule: # Her gün çalıştır
    - cron: "0 0 * * *"
  workflow_dispatch: # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Depoyu klonla
      - uses: actions/checkout@v2

      # Platane/snakes kullanarak animasyonu oluştur
      - uses: Platane/snk@v2
        with:
          github_user_name: bzynpb
          outputs: dist/github-contribution-grid-snake.svg

      # Çıktıyı "output" branch'ine pushla
      - name: Push Snake Animation to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: dist
