name: Generate Datas

on:
  schedule: # Run every 12 hours
    - cron: "0 */12 * * *"  # Trigger at the start of every 12th hour
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2  # Use the stable v2 version instead of master
        id: snake-gif
        with:
          github_user_name: bzynpb # Your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy the generated Snake SVG to GitHub Pages (output branch)
      - name: Deploy Snake Animation to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The branch to push the SVG file
          build_dir: dist        # The directory containing the SVG file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
